[package]
name = "git-shortcuts"
version = "0.1.0-rc0"
edition = "2021"

[dependencies]
git2 = "0.13"
clap = { version = "3.1.0", features = ["derive"] }
regex = "1"
phf = { version = "0.10", features = ["macros"] }
color-eyre = "0.5"
thiserror = "1.0"
lazy_static = "1.4"
